### PR TITLE
Added forge commands and YAML based configuration

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
ok to test

**Comment by jimmidyson** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
Is CI set up for this project?

**Comment by dhirajsb** [comment]
just edited the PR job config to use fusesource-ci credentials, was configured to use fuse-infra, which wasn't working

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
@jimmidyson should that have been enough to get the PR job going? it's the fabric8-profiles-pullreq job

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
ok to test

**Comment by dhirajsb** [comment]
closing without merging, going to try sending a fresh PR to fusesource CI

**Pull request closed without merging**
